- arguments: [--cpp-define=HLINT, --cpp-ansi, --cpp-include=include]

- ignore: {name: Reduce duplication}
- ignore: {name: Redundant lambda}
- ignore: {name: Use >=>}
- ignore: {name: Use const}
- ignore: {name: Use module export list}
- ignore: {name: Use lambda-case}
- ignore: {name: Use tuple-section}
- ignore: {name: Use fewer imports}

- fixity: "infixl 9 :>"
- fixity: "infixr 9 <.>, <., .>, ..."
- fixity: "infixr 9 #."
- fixity: "infixl 8 ^.., ^?, ^?!, ^@.., ^@?, ^@?!,  ^., ^@.,  ^#, .#"
- fixity: "infixr 8 ^!, ^@!"
- fixity: "infixr 4 </>~, <</>~, <.>~, <<.>~, <#~, #~, #%~, <#%~, #%%~, .|.~, .&.~, <.|.~, <.&.~, %@~, .~, +~, *~, -~, //~, ^~, ^^~, **~, &&~, <>~, ||~, %~, %%@~, <%@~, %%~, <+~, <*~, <-~, <//~, <^~, <^^~, <**~"
- fixity: "infix 4 </>=, <</>=, <.>=, <<.>=, <#=, #=, #%=, <#%=, #%%=, .|.=, .&.=, <.|.=, <.&.=, %@=, .=, +=, *=, -=, //=, ^=, ^^=, **=, &&=, <>=, ||=, %=, %%@=, <%@=, %%=, <+=, <*=, <-=, <//=, <^=, <^^=, <**="
- fixity: "infixr 2 `zoom`, `magnify`, <~, <<~"
- fixity: "infixl 1 &, &~, <&>, ??"
